2021-04-28 05:35:21,575 INFO    MainThread:13102 [wandb_setup.py:_flush():69] setting env: {}
2021-04-28 05:35:21,575 INFO    MainThread:13102 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-28 05:35:21,576 INFO    MainThread:13102 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/p3-ims-obd-savetheearth/baseline_code_apeach/wandb/run-20210428_053521-igr1hfmv/logs/debug.log
2021-04-28 05:35:21,576 INFO    MainThread:13102 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/p3-ims-obd-savetheearth/baseline_code_apeach/wandb/run-20210428_053521-igr1hfmv/logs/debug-internal.log
2021-04-28 05:35:21,576 INFO    MainThread:13102 [wandb_init.py:init():369] calling init triggers
2021-04-28 05:35:21,576 INFO    MainThread:13102 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-04-28 05:35:21,576 INFO    MainThread:13102 [wandb_init.py:init():418] starting backend
2021-04-28 05:35:21,576 INFO    MainThread:13102 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-28 05:35:21,586 INFO    MainThread:13102 [backend.py:ensure_launched():123] starting backend process...
2021-04-28 05:35:21,593 INFO    MainThread:13102 [backend.py:ensure_launched():128] started backend process with pid: 13115
2021-04-28 05:35:21,594 INFO    MainThread:13102 [wandb_init.py:init():423] backend started and connected
2021-04-28 05:35:21,595 INFO    MainThread:13102 [wandb_init.py:init():465] updated telemetry
2021-04-28 05:35:21,596 INFO    MainThread:13102 [wandb_init.py:init():484] communicating current version
2021-04-28 05:35:22,459 INFO    MainThread:13102 [wandb_init.py:init():489] got version response 
2021-04-28 05:35:22,460 INFO    MainThread:13102 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-28 05:35:22,673 INFO    MainThread:13102 [wandb_init.py:init():522] starting run threads in backend
2021-04-28 05:35:25,455 INFO    MainThread:13102 [wandb_run.py:_console_start():1524] atexit reg
2021-04-28 05:35:25,455 INFO    MainThread:13102 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-28 05:35:25,456 INFO    MainThread:13102 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-28 05:35:25,458 INFO    MainThread:13102 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-28 05:35:25,459 INFO    MainThread:13102 [wandb_init.py:init():546] run started, returning control to user process
2021-04-28 05:35:30,571 INFO    MainThread:13102 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 1
2021-04-28 05:35:30,572 INFO    MainThread:13102 [wandb_run.py:_restore():1466] restore
2021-04-28 05:35:32,790 INFO    MainThread:13102 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1331
  total_bytes: 1331
}

2021-04-28 05:35:33,691 INFO    MainThread:13102 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 1331
  total_bytes: 4022
}

2021-04-28 05:35:34,081 INFO    MainThread:13102 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4294
  total_bytes: 4294
}

2021-04-28 05:35:34,183 INFO    MainThread:13102 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4294
  total_bytes: 4294
}

2021-04-28 05:35:34,286 INFO    MainThread:13102 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4294
  total_bytes: 4294
}

2021-04-28 05:35:34,388 INFO    MainThread:13102 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4294
  total_bytes: 4294
}

2021-04-28 05:35:34,491 INFO    MainThread:13102 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4294
  total_bytes: 4294
}

2021-04-28 05:35:34,593 INFO    MainThread:13102 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4294
  total_bytes: 4294
}

2021-04-28 05:35:35,698 INFO    MainThread:13102 [wandb_run.py:_show_files():1838] logging synced files
